CREATE DATABASE IF NOT EXISTS bxh;
USE bxh;

CREATE TABLE IF NOT EXISTS leaderboard (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE, 
    owner_client_id VARCHAR(64) NULL,
    score INT NOT NULL DEFAULT 0,
    score_achieved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP --Chỉ cập nhật khi điểm thay đổi
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;