CREATE DATABASE IF NOT EXISTS bxh;
USE bxh;

CREATE TABLE IF NOT EXISTS leaderboard (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE, 
    owner_client_id VARCHAR(64) NULL,
    score INT NOT NULL DEFAULT 0,
    score_achieved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    score_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP -- Tự động cập nhật thời gian
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;